[ConsoleVariables]
; LRUCache
r.OpenGL.EnableProgramLRUCache=1
r.OpenGL.ProgramLRUBinarySize=35*1024*1024
r.OpenGL.ProgramLRUKeepBinaryResident=1
r.OpenGL.ProgramLRUCount = 700
; auto-instancing
;r.Mobile.SupportGPUScene=1
;r.Mobile.UseGPUSceneTexture=1

[/Script/Engine.Engine]
; DefaultBloomKernel is not used on mobile
DefaultBloomKernelTextureName=/Engine/EngineResources/DefaultTexture.DefaultTexture

[/Script/Engine.RendererSettings]
r.Shadow.ForceSerialSingleRenderPass=1

[DevOptions.Shaders]
NeedsShaderStableKeys=true

[/Script/AndroidRuntimeSettings.AndroidRuntimeSettings]
;DISABLE_MINIFY=0

[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInGame=524288