#pragma once

#ifdef _SERVER
#include "../../Server/Enums/SharedCommonEnum.h"
#include "../../Server/Enums/SharedSpawnEnum.h"
#include "../../Server/Enums/SharedCreatureEnum.h"
#include "../../Server/Enums/SharedIffEnum.h"
#include "../../Server/Enums/SharedMoveEnum.h"
#include "../../Server/Enums/SharedStatEnum.h"
#include "../../Server/Enums/SharedAbnormalityEnum.h"
#include "../../Server/Enums/SharedPassivityEnum.h"
#include "../../Server/Enums/SharedCombatEnum.h"
#include "../../Server/Enums/SharedSkillEnum.h"
#include "../../Server/Enums/SharedSkillNotifyEnum.h"
#include "../../Server/Enums/SharedProjectileEnum.h"
#include "../../Server/Enums/SharedItemEnum.h"
#include "../../Server/Enums/SharedMailEnum.h"
#include "../../Server/Enums/SharedQuestEnum.h"
#include "../../Server/Enums/SharedEventEnum.h"
#include "../../Server/Enums/SharedFairyEnum.h"
#include "../../Server/Enums/SharedChatEnum.h"
#include "../../Server/Enums/SharedGuildEnum.h"
#include "../../Server/Enums/SharedCostumeEnum.h"
#include "../../Server/Enums/SharedSystemMessageEnum.h"
#include "../../Server/Enums/SharedBookmarkEnum.h"
#include "../../Server/Enums/SharedMapEventEnum.h"
#include "../../Server/Enums/SharedBuddyEnum.h"
#include "../../Server/Enums/SharedPropEnum.h"
#include "../../Server/Enums/SharedMarketEnum.h"
#include "../../Server/Enums/SharedNoticeEnum.h"
#include "../../Server/Enums/SharedBossEnum.h"
#include "../../Server/Enums/SharedGameActionEnum.h"
#include "../../Server/Enums/SharedRankEnum.h"
#include "../../Server/Enums/SharedMonsterknowledgeEnum.h"
#include "../../Server/Enums/SharedAchievementEnum.h"
#include "../../Server/Enums/SharedTitleEnum.h"
#include "../../Server/Enums/SharedStatisticsEnum.h"
#include "../../Server/Enums/SharedInteractionEnum.h"
#include "../../Server/Enums/SharedMqMsgEnum.h"
#include "../../Server/Enums/SharedProfileEnum.h"
#include "../../Server/Enums/SharedPartyDungeonEnum.h"
#include "../../Server/Enums/SharedBattlePassEnum.h"
#include "../../Server/Enums/AIDataEnum.h"
#include "../../Server/Enums/KickReasonEnum.h"
#include "../../Server/Enums/PD_ResultEnum.h"
#include "../../Server/Enums/SharedBMShopEnum.h"
#include "../../Server/Enums/SharedUnlockEnum.h"
#include "../../Server/Enums/SharedCommunityEventEnum.h"
#include "../../Server/Enums/SharedGsOptionItemEnum.h"
#include "../../Server/Enums/SharedAppGuardEnum.h"

#ifndef _SHIPPING
#include "../../Server/Enums/SharedDebugEnum.h"
#endif

#else
	
#include "../../Client/SharedEnums/SharedCommonEnum.h"
#include "../../Client/SharedEnums/SharedSpawnEnum.h"
#include "../../Client/SharedEnums/SharedCreatureEnum.h"
#include "../../Client/SharedEnums/SharedIffEnum.h"
#include "../../Client/SharedEnums/SharedMoveEnum.h"
#include "../../Client/SharedEnums/SharedStatEnum.h"
#include "../../Client/SharedEnums/SharedAbnormalityEnum.h"
#include "../../Client/SharedEnums/SharedPassivityEnum.h"
#include "../../Client/SharedEnums/SharedCombatEnum.h"
#include "../../Client/SharedEnums/SharedSkillEnum.h"
#include "../../Client/SharedEnums/SharedSkillNotifyEnum.h"
#include "../../Client/SharedEnums/SharedItemEnum.h"
#include "../../Client/SharedEnums/SharedMailEnum.h"
#include "../../Client/SharedEnums/SharedQuestEnum.h"
#include "../../Client/SharedEnums/SharedEventEnum.h"
#include "../../Client/SharedEnums/SharedFairyEnum.h"
#include "../../Client/SharedEnums/SharedChatEnum.h"
#include "../../Client/SharedEnums/SharedGuildEnum.h"
#include "../../Client/SharedEnums/SharedSystemMessageEnum.h"
#include "../../Client/SharedEnums/SharedBookmarkEnum.h"
#include "../../Client/SharedEnums/SharedBuddyEnum.h"
#include "../../Client/SharedEnums/SharedMapEventEnum.h"
#include "../../Client/SharedEnums/SharedPropEnum.h"
#include "../../Client/SharedEnums/SharedCostumeEnum.h"
#include "../../Client/SharedEnums/SharedMarketEnum.h"
#include "../../Client/SharedEnums/SharedNoticeEnum.h"
#include "../../Client/SharedEnums/SharedBossEnum.h"
#include "../../Client/SharedEnums/SharedRankEnum.h"
#include "../../Client/SharedEnums/SharedMonsterknowledgeEnum.h"
#include "../../Client/SharedEnums/SharedTitleEnum.h"
#include "../../Client/SharedEnums/SharedPartyDungeonEnum.h"
#include "../../Client/SharedEnums/SharedBMShopEnum.h"
#include "../../Client/SharedEnums/SharedUnlockEnum.h"
#include "../../Client/SharedEnums/SharedCommunityEventEnum.h"
#include "../../Client/SharedEnums/SharedAppGuardEnum.h"

#endif


