[ConsoleVariables]
; LRUCache
r.OpenGL.EnableProgramLRUCache=1
r.OpenGL.ProgramLRUBinarySize=35*1024*1024
r.OpenGL.ProgramLRUKeepBinaryResident=1
r.OpenGL.ProgramLRUCount = 700

[DevOptions.Shaders]
NeedsShaderStableKeys=true

[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInGame=524288