// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GsStateLocalPlayerCasting.h"
#include "GsStateLocalPlayerAttack.h"
#include "GsStateLocalPlayerIdle.h"
#include "GsStateLocalPlayerDying.h"
#include "GsStateLocalPlayerDead.h"
#include "GsStateLocalPlayerAutoMove.h"
#include "GsStateLocalPlayerAutoMoveStop.h"
#include "GsStateLocalPlayerChangeIdle.h"
#include "GsStateLocalPlayerFreezeState.h"
#include "GsStateLocalPlayerReaction.h"
#include "GsStateLocalPlayerRevive.h"
#include "GsStateLocalPlayerRide.h"
#include "GsStateLocalPlayerRun.h"
#include "GsStateLocalPlayerSpawn.h"
#include "GsStateLocalPlayerWarp.h"
#include "GsStateLocalPlayerWalk.h"
#include "GsStateLocalPlayerHit.h"
#include "GsStateLocalPlayerInteraction.h"
#include "GsStateLocalPlayerLooting.h"
#include "GsStateLocalPlayerChangeWeapon.h"
#include "GsStateLocalPlayerInteractionEnd.h"
#include "GsStateLocalPlayerActionEnd.h"
#include "GsStateLocalPlayerSocial.h"
#include "GsStateLocalPlayerSocialAction.h"
#include "GsStateLocalPlayerChangeWeaponEnd.h"