#pragma once

/**
 * GsMessageContents 에 있는 MessageContents 의 복사본이다.
 * 특정 가이드 퀘스트를 클릭했을 때, 이에 맞는 특정 컨텐츠를 열어주어야 하는데, 이를 Data-Driven 하게 만들기 위해 정의했다.
 * MessageContents 를 DataCenter 모듈 쪽으로 옮기는 것이 제일 좋으나, 일단 나중에 여유가 있을 때 바꾸도록 한다.
 */

UENUM(BlueprintType)
enum class EGsGuideQuestWindowType : uint8
{
	ACTIVE_HUD = 0,				// HUD 활성화
	ACTIVE_WINDOW_OPTION,
	ACTIVE_WINDOW_QUEST,
	ACTIVE_WINDOW_SKILL,
	ACTIVE_WINDOW_CONTINENTALMAP,
	ACTIVE_WINDOW_REGIONMAP,
	ACTIVE_WINDOW_FAIRY,
	ACTIVE_WINDOW_NPC_SHOP,
	ACTIVE_WINDOW_GUILD,
	ACTIVE_WINDOW_COSTUME,
	ACTIVE_POPUP_BUDDY,
	ACTIVE_WINDOW_MAIL,
	ACTIVE_WINDOW_ITEM_COLLECTION,
	/*ACTIVE_WINDOW_MAILDETAIL,*/
	ACTIVE_WINDOW_DUNGEON,
	CLOSE_WINDOW_DUNGEON,
	ACTIVE_WINDOW_NPC_DEPOT,
	ACTIVE_WINDOW_MULTI_LEVEL_RANK,
	ACTIVE_WINDOW_MARKET,
	ACTIVE_WINDOW_CRAFT,
	ACTIVE_WINDOW_COMMUNITY,
	ACTIVE_QUICK_MENU, // 햄버거 메뉴 열림
	CLOSE_QUICK_MENU, // 햄버거 메뉴 닫으라고 메시지보냄
	ACTIVE_OFFLINEPLAY,
	ACTIVE_BMSHOP,
	/*ACTIVE_POPUP_BOSS,*/
	ACTIVE_WINDOW_RANKING,
	ACTIVE_SAVE_BATTERY,
	ACTIVE_WINDOW_ACHIEVEMENT,
	ACTIVE_WINDOW_MONSTER_COLLECTION,
	ACTIVE_INVENTORY,
	ACTIVE_TITLE,
	ACTIVE_WINDOW_GAME_STATISTICS,
	ACTIVE_WINDOW_USER_PROFILE,	
	ACTIVE_BOSS,
	ACTIVE_WINDOW_QUEST_BOARD,
	ACTIVE_WINDOW_PK_BOOK,
	CLOSE_WINDOW_PK_BOOK,
	ACTIVE_WINDOW_REPAIR,		// 아이템 장비 복구 Window
	ACTIVE_WINDOW_RECOMPOSE,	// 페어리 및 코스튬 재합성 Window
	ACTIVE_WINDOW_KEYBOARD_MAPPING,	// 윈도우 키보드맵핑 Window
	ACTIVE_WINDOW_INVADE,		// 2023/1/20 PKT - 침공전
	ACTIVE_WINDOW_SEAL,
	ACTIVE_WINDOW_BATTLEPASS,
	ACTIVE_WINDOW_SIEGE_WARFARE,
	ACTIVE_WINDOW_EXCHANGE_CUSTUME,
	ACTIVE_WINDOW_SPIRIT_SHOT,

	REQ_ACTIVE_WINDOW_INVADE,
};