[Android DeviceProfile]
; Globcal Scale-Factor
;+CVars=r.MobileContentScaleFactor=1
+CVars=r.ShaderPipelineCache.Enabled=1
;+CVars=r.ShaderPipelineCache.LogPSO=1
;+CVars=r.ShaderPipelineCache.SaveBoundPSOLog=1
+CVars=r.ShaderPipelineCache.StartupMode=0
+CVars=Slate.ForceBackgroundBlurLowQualityOverride=0

[IOS DeviceProfile]
; Globcal Scale-Factor
;+CVars=r.MobileContentScaleFactor=1
+CVars=r.ShaderPipelineCache.Enabled=1
;+CVars=r.ShaderPipelineCache.LogPSO=1
;+CVars=r.ShaderPipelineCache.SaveBoundPSOLog=1
+CVars=r.ShaderPipelineCache.StartupMode=0
+TextureLODGroups=(Group=TEXTUREGROUP_WorldNormalMap,MinLODSize=1,MaxLODSize=16384,LODBias=1,MinMagFilter=aniso,MipFilter=point,MipGenSettings=TMGS_SimpleAverage)

[iPhoneXS DeviceProfile]
DeviceType=IOS
BaseProfileName=iPhone8
+CVars=r.CustomUnsafeZones="(L:free[0,-15][812,15]);(P:fixed[83,0][206,30])"

[iPhoneXSMax DeviceProfile]
DeviceType=IOS
BaseProfileName=iPhone8
+CVars=r.CustomUnsafeZones="(L:free[0,-15][896,15]);(P:fixed[104,0][206,30])"

[iPadPro3_129 DeviceProfile]
DeviceType=IOS
BaseProfileName=IPadPro

[Android_Mali_G78 DeviceProfile]
+CVars=r.DefaultBackBufferPixelFormat=0