#pragma once

class FGsContentsMode
{
public:
	enum InLobby
	{
		INTRO = 0,
		LOGIN,
		SERVER_SELCET,
		CHARACTER_SELECT,
		CHARACTER_CREATE,
		CHARACTER_CUSTOMIZING,
		CHARACTER_CREATE_EMPTY_STATE,
		TITLE,
		PATCH,
		REPAIR_CHECK,
		PATCH_CHECK,
		HIVE_AUTH,
		HIVE_INIT,
		HIVECHECK_MAINTENANCE,
		HIVECHECK_AUTH_MAINTENANCE,
		HIVECHECK_GATEWAY_MAINTENANCE,
		DIVERGENCE,
		NETADDRESS_SELECT,
		ID_PASSWORD,
		OFFLINE_PLAY_BACKGROUND,
		HUD,
		NETCHECK_HANDSHAKECOMPLETED,
		HERCULES_AUTH,
		PRE_PLAYABLE_MOVIE,
		POST_PLAYABLE_MOVIE,
		Z_PAY,
		MAX,
	};

	enum InGame
	{
		ContentsHud = 0,
		ContentsShop,
		ContentsNpcShop,
		ContentsSkill,
		ContentsOption,
		ContentsQuest,
		ContentsContinentalMap,
		ContentsRegionMap,
		ContentsFairy,
		ContentsGuild,
		ContentsCostume,
		ContentsMail,
		ContentsItemCollection,
		ContentsDungeon,
		ContentsNpcDepot,
		ContentsMarket,
		ContentsMultiLevelRank,
		ContentsOfflinePlay,
		ContentsCraft,
		ContentsBMShop,
		ContentsCommunity,
		ContentsBoss,
		ContentsRanking,
		ContentsAchievement,
		ContentsMonsterCollection,
		ContentsTitle,
		ContentsGameStatistics,
		ContentsUserProfile,
		ContentsQuestBoard,
		ContentsPKBook,
		ContentsRepair,
		ContentsRecompose,
		ContentsKeyBoardMapping,
		ContentsInvade,
		ContentsSeal,
		ContentsBattlePass,
		ContentsSiegeWarfare,
		ContentsExchangeCostume,
		ContentsSpiritShot,
		ContentsAgitDungeon,
		ContentsStarLegacy,
		GameMax,		
	};
};