#pragma once

#include "EGsUISituation.generated.h"

UENUM(BlueprintType)
enum class  EGsSituation : uint8
{
	NONE,
	INVASION_CARRIAGE_SUVIVE,
	INVASION_CARRIAGE_DESTROYED,
	INVASION_VICTORY,
	INVASION_DEFEATE,
	INVASION_TEMPLE_KNIGHT_DEATH,
	INVASION_CARRIAGE_SPAWN,
	INVASION_DEPAWN_MONSTER_SPAWN,
};
