#pragma once

#include "EGsUIColorType.generated.h"

UENUM(BlueprintType)
enum class EGsUIColorType : uint8
{
	NONE = 0,

	// 시스템 컬러

	// 상태이상 컬러
	ABNORMALITY_POSITIVE UMETA(DisplayName="ABNORMALITY_POSITIVE(상태이상 버프)"),
	ABNORMALITY_NEGATIVE UMETA(DisplayName="ABNORMALITY_NEGATIVE(상태이상 디버프)"),
	PASSIVE_POSITIVE UMETA(DisplayName="PASSIVE_POSITIVE(패시브 버프)"),
	PASSIVE_NEGATIVE UMETA(DisplayName="PASSIVE_NEGATIVE(패시브 디버프)"),
	PASSIVE_NEGATIVE_ENV UMETA(DisplayName="PASSIVE_NEGATIVE_ENV(패시브 환경 디버프)"),
 
	// Item Icon Grade Color
	ITEM_GRADE_NORMAL UMETA(DisplayName = "ITEM_GRADE_NORMAL"),
	ITEM_GRADE_MAGIC UMETA(DisplayName = "ITEM_GRADE_MAGIC"),
	ITEM_GRADE_RARE	UMETA(DisplayName = "ITEM_GRADE_RARE"),
	ITEM_GRADE_EPIC	UMETA(DisplayName = "ITEM_GRADE_EPIC"),
	ITEM_GRADE_UNIQUE UMETA(DisplayName = "ITEM_GRADE_UNIQUE"),
	ITEM_GRADE_LEGEND UMETA(DisplayName = "ITEM_GRADE_LEGEND"),
	ITEM_GRADE_ETERNAL UMETA(DisplayName = "ITEM_GRADE_ETERNAL"),

	// Inven Weight UI Color
	WEIGHT_NORMAL UMETA(DisplayName = "NORMAL_WEIGHT(정상무게 상태)"),
	WEIGHT_PENALTY_ONE UMETA(DisplayName = "PENALTY_ONE(첫번째 패널티 상태)"),
	WEIGHT_PENALTY_TWO UMETA(DisplayName = "PENALTY_TWO(두번째 패널티 상태)"),

	// Stat Color
	DEFAULT_STAT_COLOR UMETA(DisplayName = "DEFAULT_STAT_COLOR(활성화 스텟_Default상태)"),
	DISABLE_STAT_COLOR UMETA(DisplayName = "DISABLE_STAT_COLOR(비활성화 스텟)"),
	UP_COMPARE_STAT_COLOR UMETA(DisplayName = "UP_COMPARE_STAT_COLOR(스텟비교_상승 화살표)"),
	DOWN_COMPARE_STAT_COLOR UMETA(DisplayName = "DOWN_COMPARE_STAT_COLOR(스텟비교_하락 화살표)"),

	// 혼잡도 표시
	CONGESTION_LOW UMETA(DisplayName = "CONGESTION_LOW(혼잡도 낮음)"),
	CONGESTION_MEDIUM UMETA(DisplayName = "CONGESTION_MEDIUM(혼잡도 원활)"),
	CONGESTION_HIGH UMETA(DisplayName = "CONGESTION_HIGH(혼잡도 혼잡)"),
	CONGESTION_FULL UMETA(DisplayName = "CONGESTION_FULL(혼잡도 포화)"),

	// Enchant UI
	ENCHANT_WARNING_DESTROY UMETA(DisplayName = "ENCHANT_WARNING_DESTROY (강화UI - 파괴Text Color)"),
	ENCHANT_WARNING_NORMAL UMETA(DisplayName = "ENCHANT_WARNING_NORMAL (강화UI - 안전Text Color)"),
	ENCHANT_EXPECT_VALUE UMETA(DisplayName = "ENCHANT_EXPECT_VALUE (강화UI - 강화시 예상되는 값 출력 Color)"),
	ENCHANT_EXPECT_GAIN_OPTION UMETA(DisplayName = "ENCHANT_EXPECT_GAIN_OPTION (강화UI - 강화시 예상되는 특성옵션 출력 Color)"),
	ENCHANT_CURSED_EXPECT_VALUE UMETA(DisplayName = "ENCHANT_CURSED_EXPECT_VALUE (강화UI - 저주 강화시 예상되는 값 출력 Color)"),
	ENCHANT_NEED_COST UMETA(DisplayName = "ENCHANT_NEED_COST (강화UI - 비용부족 Text Color)"),
	ENCHANT_ENOUGH_COST UMETA(DisplayName = "ENCHANT_ENOUGH_COST (강화UI - 비용충분 Text Color)"),

	BMSHOP_MILEAGE_TEXT_COLOR UMETA(DisplayName = "BMSHOP_MILEAGE_TEXT_COLOR (BM 상점 마일리지 출력 텍스트 컬러)"),

	// Quest UI
	QUEST_MAIN_TITLE_COLOR UMETA(DisplayName = "QUEST_MAIN_TITLE_COLOR(퀘스트메인 허드 타이틀Text Color)"),
	QUEST_SUB_TITLE_COLOR UMETA(DisplayName = "QUEST_SUB_TITLE_COLOR(퀘스트서브 허드 타이틀Text Color)"),
	QUEST_GUIDE_TITLE_COLOR UMETA(DisplayName = "QUEST_SUB_TITLE_COLOR(퀘스트가이드 허드 타이틀Text Color)"),

	// LocalPlayer
	LOCAL_PLAYER_DEFAULT UMETA(DisplayName = "LOCAL_PLAYER_DEFAULT(내 캐릭터 네임 기본)"),
	
	// RemotePlayer
	REMOTE_PLAYER_ENEMY UMETA(DisplayName = "REMOTE_PLAYER_ENEMY(타유저 적)"),
	REMOTE_PLAYER_PARTY UMETA(DisplayName = "REMOTE_PLAYER_PARTY(타유저 파티원)"),
	REMOTE_PLAYER_ALLY UMETA(DisplayName = "REMOTE_PLAYER_PARTY(타유저 아군)"),
	REMOTE_PLAYER_MY_GUILD UMETA(DisplayName = "REMOTE_PLAYER_MY_GUILD(나와 같은 길드 유저)"),
	REMOTE_PLAYER_DEFAULT_INTERSERVER UMETA(DisplayName = "REMOTE_PLAYER_DEFAULT_INTERSERVER(인터서버 유적 기본 컬러)"),

	// GM Player
	GM_PLAYER_DEFAULT UMETA(DisplayName = "GM_PLAYER_DEFAULT(GM 캐릭터 네임 기본)"),

	//...
	NORMAL_TEXT_COLOR UMETA(DisplayName = "NORMAL_TEXT_COLOR(일반 텍스트 컬러)"),
	HIGHLIGHT_TEXT_COLOR UMETA(DisplayName = "HIGHLIGHT_TEXT_COLOR(강조시 사용하는 텍스트 컬러)"),

	NPCDIALOG_MY_COLOR UMETA(DisplayName = "NPCDIALOG_MY_COLOR(Npc다이얼로그 - 내 대사 컬러)"),
	NPCDIALOG_BASE_COLOR UMETA(DisplayName = "NPCDIALOG_BASE_COLOR(Npc다이얼로그 - 기본 대사 컬러)"),
	NPCDIALOG_MY_NAME_COLOR UMETA(DisplayName = "NPCDIALOG_MY_NAME_COLOR(Npc다이얼로그 - 내 이름 컬러)"),
	NPCDIALOG_BASE_NAME_COLOR UMETA(DisplayName = "NPCDIALOG_BASE_NAME_COLOR(Npc다이얼로그 - 기본 이름 컬러)"),
	NPCDIALOG_FAIRY_NAME_COLOR UMETA(DisplayName = "NPCDIALOG_BASE_NAME_COLOR(Npc다이얼로그 - 페어리 컬러)"),
	
	// ItemGrade BG 컬러
	ITEM_BG_GRADE_NORMAL UMETA(DisplayName = "ITEM_BG_GRADE_NORMAL"),
	ITEM_BG_GRADE_MAGIC UMETA(DisplayName = "ITEM_BG_GRADE_MAGIC"),
	ITEM_BG_GRADE_RARE	UMETA(DisplayName = "ITEM_BG_GRADE_RARE"),
	ITEM_BG_GRADE_EPIC	UMETA(DisplayName = "ITEM_BG_GRADE_EPIC"),
	ITEM_BG_GRADE_UNIQUE UMETA(DisplayName = "ITEM_BG_GRADE_UNIQUE"),
	ITEM_BG_GRADE_LEGEND UMETA(DisplayName = "ITEM_BG_GRADE_LEGEND"),
	ITEM_BG_GRADE_ETERNAL UMETA(DisplayName = "ITEM_BG_GRADE_ETERNAL"),

	BUDDY_ONLINE_COLOR UMETA(DisplayName = "BUDDY_ONLINE_COLOR"),
	BUDDY_OFFLINE_COLOR UMETA(DisplayName = "BUDDY_OFFLINE_COLOR"),

	FREE_RESTORE_PENALTY_VALID_COLOR UMETA(DisplayName = "FREE_RESTORE_PENALTY_VALID_COLOR"),
	FREE_RESTORE_PENALTY_INVALID_COLOR UMETA(DisplayName = "FREE_RESTORE_PENALTY_INVALID_COLOR"),

	// 개선: 컬러 사용이 특이해서 분리했는데, 나중에 정리 필요
	GUILD_DONATION_VALID UMETA(DisplayName = "GUILD_DONATION_VALID(길드기부 가능)"),
	GUILD_DONATION_INVALID UMETA(DisplayName = "GUILD_DONATION_INVALID(길드기부 불가능)"),

	// 기본적으로 사용될 수 있는 항목 추가(예외가 있을 때만 색 추가하도록)
	DEFAULT_VALID UMETA(DisplayName = "DEFAULT_VALID(기본 가능상황 컬러)"),
	DEFAULT_INVALID UMETA(DisplayName = "DEFAULT_INVALID(기본 불가능상황 컬러)"),
	DEFAULT_ENOUGH UMETA(DisplayName = "DEFAULT_ENOUGH(기본 충분함 컬러)"),
	DEFAULT_LACK UMETA(DisplayName = "DEFAULT_LACK(기본 부족함 컬러)"),
	DEFAULT_DISABLE UMETA(DisplayName = "DEFAULT_DISABLE(기본 비활성화 컬러)"),

	PVP_ALIGNMENT_NEUTRALITY UMETA(DisplayName = "PVP_ALIGNMENT_NEUTRALITY(PVP 성향 중립)"),
	PVP_ALIGNMENT_THREAT UMETA(DisplayName = "PVP_ALIGNMENT_THREAT(PVP 성향 위협)"),
	PVP_ALIGNMENT_CHAOS UMETA(DisplayName = "PVP_ALIGNMENT_CHAOS(PVP 성향 혼돈)"),

	// 길드 창에서 적대 길드 컬러표시(PVP_ALIGNMENT_CHAOS 컬러가 창에서 쓰기엔 너무 밝다고 해서 새로 추가)
	GUILD_DEFAULT_COLOR UMETA(DisplayName = "GUILD_DEFAULT_COLOR(길드창 일반/동맹길드 컬러)"),
	GUILD_ENEMY_COLOR UMETA(DisplayName = "GUILD_ENEMY_COLOR(길드창 적대길드 컬러)"),
	GUILD_ALLY_COLOR UMETA(DisplayName = "GUILD_ALLY_COLOR(길드창 동맹길드 컬러)"),

	MULTILEVELRANK_QUEST_NORMAL_COLOR UMETA(DisplayName = "MULTILEVELRANK QUEST DEFAULT_COLOR(다단계 랭크 퀘스트 기본 컬러)"),
	MULTILEVELRANK_QUEST_INPROGRESS UMETA(DisplayName = "MULTILEVELRANK QUEST INPROGRESS_COLOR(다단계 랭크 퀘스트 진행 중 컬러)"),
	MULTILEVELRANK_QUEST_COMPLECTED UMETA(DisplayName = "MULTILEVELRANK QUEST COMPLECTED_COLOR(다단계 랭크 퀘스트 완료 중 컬러)"),

	OPTION_NORMAL_COLOR UMETA(DisplayName = "OPTION_NORMAL_COLOR(옵션 기본 컬러)"),
	OPTION_MAIN_COLOR UMETA(DisplayName = "OPTION_MAIN_COLOR(옵션 메인 컬러)"),
	OPTION_SUB_COLOR UMETA(DisplayName = "OPTION_SUB_COLOR(옵션 서브 컬러)"),
	OPTION_RED_COLOR UMETA(DisplayName = "OPTION_RED_COLOR(옵션 레드(강조,경고) 컬러)"),

	TREASURE_MONSTER_OWN  UMETA(DisplayName = "TREASURE_MONSTER_OWN(로컬 플레이어 의 보물 몬스터 네임 컬러)"),
	TREASURE_MONSTER_OTHER  UMETA(DisplayName = "TREASURE_MONSTER_OTHER(타 플레이어 의 보물 몬스터 네임 컬러)"),
	TREASURE_MONSTER_TEAM  UMETA(DisplayName = "TREASURE_MONSTER_TEAM(길드 플레이어 또는 파티 플레이어 의 보물 몬스터 네임 컬러)"),
	TREASURE_MONSTER_TIME  UMETA(DisplayName = "TREASURE_MONSTER_TIME(플레이어 의 보물 몬스터 남은 시간 컬러)"),

	MAPNAME_PUBLIC_FIELD UMETA(DisplayName = "MAPNAME_PUBLIC_FIELD(맵이름 퍼블릭 필드)"),
	MAPNAME_PUBLIC_DUNGEON UMETA(DisplayName = "MAPNAME_PUBLIC_DUNGEON(맵이름 퍼블릭 던전)"),

	ITEM_REFINE_HIGH UMETA(DisplayName = "ITEM_REFINE_HIGH(아이템 제련 최상급 컬러)"),
	ITEM_REFINE_MIDDLE UMETA(DisplayName = "ITEM_REFINE_MIDDLE(아이템 제련 상급 컬러)"),
	ITEM_REFINE_LOW UMETA(DisplayName = "ITEM_REFINE_LOW(아이템 제련 하급 컬러)"),

	// 스킬 레벨 기본 컬러, 보너스가 있을 경우의 컬러
	SKILL_LEVEL_DEFAULT UMETA(DisplayName = "SKILL_LEVEL_DEFAULT(스킬 레벨 기본컬러)"),
	SKILL_LEVEL_ADD_BONUS UMETA(DisplayName = "SKILL_LEVEL_BONUS(보너스 레벨이 더해진 스킬 컬러)"),

	DUNGEON_DIFFICULTY_TYPE_EASY UMETA(DisplayName = "DUNGEON_DIFFICULTY_TYPE_EASY(던전 난이도 쉬움)"),
	DUNGEON_DIFFICULTY_TYPE_NORMAL UMETA(DisplayName = "DUNGEON_DIFFICULTY_TYPE_NORMAL(던전 난이도 보통)"),
	DUNGEON_DIFFICULTY_TYPE_DIFFICULT UMETA(DisplayName = "DUNGEON_DIFFICULTY_TYPE_DIFFICULT(던전 난이도 어려움)"),
	DUNGEON_DIFFICULTY_TYPE_NIGHTMARE UMETA(DisplayName = "DUNGEON_DIFFICULTY_TYPE_NIGHTMARE(던전 난이도 극악)"),

	TITLE_HUD_GRADE_NORMAL UMETA(DisplayName = "TITLE_HUD_GRADE_NORMAL"),
	TITLE_HUD_GRADE_MAGIC UMETA(DisplayName = "TITLE_HUD_GRADE_MAGIC"),
	TITLE_HUD_GRADE_RARE	UMETA(DisplayName = "TITLE_HUD_GRADE_RARE"),
	TITLE_HUD_GRADE_EPIC	UMETA(DisplayName = "TITLE_HUD_GRADE_EPIC"),
	TITLE_HUD_GRADE_UNIQUE UMETA(DisplayName = "TITLE_HUD_GRADE_UNIQUE"),
	TITLE_HUD_GRADE_LEGEND UMETA(DisplayName = "TITLE_HUD_GRADE_LEGEND"),

	TITLE_INVADE_BATTLE_LEVEL	UMETA(DisplayName = "TITLE_INVADE_BATTLE_LEVEL(침공 전투 칭호)"),

	COLLECTION_IMMEDIATE_POSSIBLE		UMETA(DisplayName = "COLLECTION_IMMEDIATE_POSSIBLE(컬렉션 즉시 등록 가능)"),
	COLLECTION_CONDITIONAL_POSSIBLE		UMETA(DisplayName = "COLLECTION_CONDITIONAL_POSSIBLE(컬렉션 조건부 등록 가능)"),
	COLLECTION_IMPOSSIBLE				UMETA(DisplayName = "COLLECTION_IMPOSSIBLE(컬렉션 등록 불가능)"),

	MULTILEVELRANK_NORMAL UMETA(DisplayName = "MULTILEVELRANK_NORMAL(승급 컨텐츠 일반 슬롯 상단 텍스트 색상)"),
	MULTILEVELRANK_PLEDGE UMETA(DisplayName = "MULTILEVELRANK_PLEDGE(승급 컨텐츠 서약 슬롯 상단 텍스트 색상)"),

	GUILD_DIVISION_STATE_NORMAL UMETA(DisplayName = "GUILD_DIVISION_STATE_NORMAL(기사단 분배_상태 일반)"),
	GUILD_DIVISION_STATE_ENOUGH UMETA(DisplayName = "GUILD_DIVISION_STATE_ENOUGH(기사단 분배_상태 시간 충분)"),
	GUILD_DIVISION_STATE_NOT_ENOUGH UMETA(DisplayName = "GUILD_DIVISION_STATE_NOT_ENOUGH(기사단 분배_상태 시간 부족)"),
	GUILD_AUCTION_NORMAL UMETA(DisplayName = "GUILD_AUCTION_NORMAL(기사단 경매_일반 경매 캐릭터명)"),
	GUILD_AUCTION_APPOINTMENT UMETA(DisplayName = "GUILD_AUCTION_APPOINTMENT(기사단 경매_지정 경매 캐릭터명)"),

	CODEX_MAPGROUP_LEVEL_UP UMETA(DisplayName = "CODEX_MAPGROUP_LEVEL_UP(도감 맵그룹 레벨업 가능시 사용할 황금색)"),

	ITEM_COLLECTION_REGISTER UMETA(DisplayName = "ITEM_COLLECTION_REGISTER(아이템 컬렉션 등록 완성 상태)"),
	ITEM_COLLECTION_UNREGISTER UMETA(DisplayName = "ITEM_COLLECTION_UNREGISTER(아이템 컬렉션 등록 미완성 상태)"),
};
